name: Create a js-bundle
on: [push]
jobs:
  bundle_js:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '12'
      - run: npm install
      - name: Building a bundled app
        run: npm run build
      - name: Adding roboto font & material icons for offline use
        run: |
          npm run add-roboto
          npm run add-icons
      - name: Zipping and uploading
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: dist/**
